NWBFile:
  session_id: "session250901" # required by DANDI 
  session_description: "Project " # required by NWB
  session_start_time: "1900-01-01T08:15:30-05:00" # required by NWB， no need to change
  lab: "BLab@PKU"
  institution: "Peking University"
  experimenter:
    - "Last, First"
    - "Last, First M."
  experiment_description: "None"
  keywords:
    - "visual processing"
    - "neuropixels"
  notes: "None" # Notes about the experiment.
  related_publications:
    - ""
  data_collection: "situation of the experiment" # Notes about data collection and analysis
  stimulus_notes: "None" # Notes about stimuli, such as how and where presented

Subject:
  subject_id: "MaoDan" # required by DANDI
  description: "good monkey"
  species: "Macaca mulatta" # required by DANDI
  sex: "M" # required by DANDI
  age: "P4Y" # required by DANDI
  weight: "12.8kg"